### ISSUE TITLE
Filling syslog MultiLoadApplet Permission denied 

### ISSUE THREAD

**Issue by skaox** [mate-desktop/mate-system-monitor#262]
#### Actual behaviour

Filling syslog / auth.log

auth.log or syslog (not sure sorry) took few gigas over the night
when I forgot to close system monitor with file systems tab open

20.04 have less than 10gb of free space on / trying to optimize for not moving data or reinstalling
when something is eating space there is a system message around 2g sorry it was a morning was
in a bit of panic so not sure who was filling auth.log/syslog didn't open those big files to verify and
don't want try another time sorry also had a few others software opened (firefox for ex.) like I said
not sure who's guilty tell me if I'm wrong nothing to report since about free space.

Operation not permitted on both Ubuntu 20.04/22.04 mate 1.24/1.26

Hope this could help. Thanks

#### Steps to reproduce the behaviour

System Monitor -> Files Systems (tab)

journalctl -f
```
org.mate.panel.applet.MultiLoadAppletFactory[100250]: glibtop(c=100250): [WARNING] statvfs '/run/user/1000/doc' failed: Operation not permitted
org.mate.panel.applet.MultiLoadAppletFactory[100250]: glibtop(c=100250): [WARNING] statvfs '/root/.cache/doc' failed: Permission denied
org.mate.panel.applet.MultiLoadAppletFactory[100250]: glibtop(c=100250): [WARNING] statvfs '/root/.cache/gvfs' failed: Permission denied
same thing
over and
over again
```

#### MATE general version

20.04  :  1.24.0
22.04  :  1.26.0

#### Package version

mate-system-monitor

20.04  :  1.24.1-0
22.04  :  1.26.0-1

#### Linux Distribution

Ubuntu Mate
20.04.6 / 22.04.4

**Comment by zhuyaliang** [comment]
Please provide a detailed explanation of the issue, otherwise I will not be able to reproduce and fix it. thanks

**Comment by skaox** [comment]
> Please provide a detailed explanation of the issue, otherwise I will not be able to reproduce and fix it. thanks

Sorry ; hope this is enough.

**Comment by skaox** [comment]
org.**mate.panel.applet**.MultiLoadAppletFactory

Problem is coming from system monitor mate panel applet.
If removed no more operation not permitted in journalctl
when system monitor file systems tab is open.

Didn't search suppose wrong GitHub ?
mate-panel - **applet** - system-monitor

Sad cause like it but should also survive without :-)

Thanks

**Comment by lukefromdc** [comment]
I was just unable to duplicate this on Debian (though under wayland this should not affect this sort of
permissions issue). I created a second panel, put the system monitor on it, and from that opened
mate-system-monitor and the "filesystems" tab. Neither that nor using the applet to monitor disks
created the warnings here. 

We need to find out what is different here

**Comment by skaox** [comment]
**Ubuntu Mate** 20.04 / 22.04 both with x11 and lightdm
```
echo $XDG_SESSION_TYPE
x11
```
if there is something I can do tell what you need ?

**Comment by lukefromdc** [comment]
I've never seen this in an x11 session either, having never seen it I really cannot work on it. My guess is this will have to wait for someone on the team who can duplicate it to work on it. Could very well be specific to Ubuntu or even to just an install with a bad or corrupted file somewhere.

Just the other night, I had to nuke from orbit and restore my root partition from backup after a lockup and forced power cycle corrupted something I was unable to find, causing icons not to appear in menus. Since I cannot stand removing icons from menus and could not find the problem, I threw in the towel, remade my root partition, then re-updated and the problem did not return.

If you have enough bandwidth to download installers and something to put it on(not everyone does, I do not), seeing if this appears on a new Ubuntu MATE install would tell if this is at least Ubuntu-wide or perhaps a problem stemming from a bad update or upgrade.

**Comment by skaox** [comment]
22.04 is almost new and BOTH UBUNTU MATE (not debian) have the same problem.
Thank you anyway

**Comment by lukefromdc** [comment]
Two Ubuntu MATE systems with this imply an Ubuntu-specific problem, you should open an issue there
