### ISSUE TITLE
mate-system-monitor shows one CPU too much

### ISSUE THREAD

**Issue by ernsteiswuerfel** [mate-desktop/mate-system-monitor#89]
May I bring the following downstream bug-report to your attention:
https://bugs.launchpad.net/ubuntu/+source/mate-system-monitor/+bug/1615846

mate-system-monitor shows one CPU too much, whichs means 2 CPUs on a single-core system, 3 CPUs on a dual-core system. The superfluous cpu always shows 0 % activity. All of my PowerPC-machines are affected since MATE 1.14.x, running MATE on Ubuntu or Gentoo. Last version worked as supposed was the MATE 1.12.x series.

This seems to be a PPC-specific issue, my amd64-boxes do not show this behaviour.

**Comment by bdejean** [comment]
Hello, it's more likely a libgtop issue. Which version do you have on your system ? Thanks to your /proc/cpuinfo, I should be able to fix it.

**Comment by ernsteiswuerfel** [comment]
Thanks for your quick reply! On Ubuntu MATE 17.04 it's libgtop-2.34.1, on Gentoo it's libgtop-2.32.0.

# cat /proc/cpuinfo 
processor	: 0
cpu		: PPC970MP, altivec supported
clock		: 1150.000000MHz
revision	: 1.1 (pvr 0044 0101)

processor	: 1
cpu		: PPC970MP, altivec supported
clock		: 1150.000000MHz
revision	: 1.1 (pvr 0044 0101)

timebase	: 33333333
platform	: PowerMac
model		: PowerMac11,2
machine		: PowerMac11,2
motherboard	: PowerMac11,2 MacRISC4 Power Macintosh 
detected as	: 337 (PowerMac G5 Dual Core)
pmac flags	: 00000000
L2 cache	: 1024K unified
pmac-generation	: NewWorld

**Comment by monsta** [comment]
Oh, looks like that additional section in this output was causing the problem for libgtop:
https://git.gnome.org/browse/libgtop/commit/?id=47bcd423b5e58210d0283b09951ea3a68f54bb7e

**Comment by monsta** [comment]
So this should be fixed in libgtop 2.30, and gnome-system-monitor also uses libgtop for getting number of CPUs since 3.18 (https://github.com/mate-desktop/mate-system-monitor/commit/db4046a313255440eb8432680aa4c920a7813c98 was picked from [this commit](https://git.gnome.org/browse/gnome-system-monitor/commit/?id=549e2e3308620810dd795321d02f041e8ab58d29)).

**Comment by ernsteiswuerfel** [comment]
Thanks for your efforts, glad you found the source of the problem! But I am a bit confused now - you said it would be fixed in libgtop 2.30, but I run libgtop 2.32/2.34.

**Comment by monsta** [comment]
I'm confused as well... I even checked the source package from Ubuntu 16.10, it's 2.34.1, and the fix is indeed in the code there. It should just work... :confused: 

Can you check gnome-system-monitor on your PPC machine just in case?

**Comment by ernsteiswuerfel** [comment]
Just checked it out, same issue with gnome-system-monitor. Ubuntu MATE 16.10, gnome-system-monitor-3.22.0.

**Comment by monsta** [comment]
@bdejean: maybe you could give us some hints about this?

**Comment by bdejean** [comment]
Hello, the libgtop part should be fixed by this https://github.com/GNOME/libgtop/commit/1a103bf142856ec129eb124d1dae70ddb3dd02e8 . Meaning that with next libgtop stable version, the number of CPUs will be again correctly detected. I had a ppc 10 years ago (main computer), looks like someone changed the cpuinfo format.

**Comment by monsta** [comment]
Thanks!
Not sure if Ubuntu would accept a patch though... Debian and Ubuntu seem to be dropping ppc support for upcoming releases, it's mentioned in this announcement:
https://ubuntu-mate.org/blog/ubuntu-mate-zesty-alpha2/

**Comment by ernsteiswuerfel** [comment]
Many thanks **bdejean**!

Debian and Ubuntu may cease to be supported, but Gentoo is alive and well. ;) So I really appreciate that this bug is resolved upstream.

Ubuntu MATE 16.04.x LTS continues to be supported (but MATE-1.12.x used here does not seem to be affected).

**Comment by monsta** [comment]
Well, 1.12 isn't affected because it used a bit different code to get the number of CPUs. It was before 1.14 release when https://github.com/mate-desktop/mate-system-monitor/commit/db4046a313255440eb8432680aa4c920a7813c98 was added to make better use of libgtop's functionality, which unfortunately also triggered this bug.

Ok, I'm closing it as it's fixed in libgtop now.
